name: Deploy to GitHub Pages

on:
  push:
    branches: [master] # or 'main'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4   # ⬅️ update to v4

      - name: Install, build, and upload site
        uses: withastro/action@v2   # ⬅️ update Astro action (v2 supports latest)

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3   # ⬅️ update to v3 (fixes v3 deprecation issue)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4   # ⬅️ update to v4
