name: Deploy to GitHub Pages

on:
  push:
    branches: [master] # or 'main'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Install, build, and upload site
        uses: withastro/action@v2
        with:
          package-manager: npm   # or pnpm / yarn depending on your project
          node-version: 20
          # no need for upload-artifact: false
          # Astro auto-uploads the dist/ folder as a GitHub Pages artifact

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
